---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Deploy-app
  labels:
    app:caddy
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: caddy 
  strategy:
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 30%
  template: 
    metadata: 
      name: Deploy-app
      labels:
        app: caddy 
    spec: 
      activeDeadlineSeconds: 5
      containers: 
        - name: caddy
          image: hema789/deploy:v1.0
          ports:
            - name: caddy
              containerPort: 80
              protocol: TCP

  

