---
apiVersion: v1
kind: Service
metadata:
  name: servicefile 
  labels:
    app: caddy
spec:
  type: Lodebalancer 
  selector: 
    app: caddy
  ports:
    - name: caddy
      protocol: TCP
      port: 80
      targetPort: 80

    